// Auto-generated by atlas-daily-scan — 2026-04-13
window.PAPERS_FEED = {
  "last_updated": "2026-04-13",
  "papers": [
    {
      "id": "biorxiv_10.1101_2024.05.26.595966",
      "title": "Complementary vertebrate Wac models exhibit phenotypes relevant to DeSanto-Shinawi Syndrome",
      "authors": "Lee K-H, Stafford AM, Pacheco-Vergara M, et al.",
      "journal": "bioRxiv",
      "date": "2026-04-12",
      "source": "biorxiv",
      "score": 23,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "First comprehensive vertebrate WAC models. Mouse and zebrafish knockouts show GABAergic neuron impacts, seizure susceptibility, and autism-relevant behaviors.",
      "doi": "10.1101/2024.05.26.595966",
      "url": "https://www.biorxiv.org/content/10.1101/2024.05.26.595966v4"
    },
    {
      "id": "biorxiv_10.64898_2026.04.10.717844",
      "title": "EVEE: Interpretable variant effect prediction from genomic foundation model embeddings",
      "authors": "Pearce MT, Dooms T, Yamamoto R, et al.",
      "journal": "bioRxiv",
      "date": "2026-04-11",
      "source": "biorxiv",
      "score": 25,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "SOTA variant effect prediction using Evo 2 7B-parameter genomic foundation model. 0.997 AUROC on 839k ClinVar SNVs. Pre-computed for 4.2M ClinVar variants via EVEE web tool.",
      "doi": "10.64898/2026.04.10.717844",
      "url": "https://www.biorxiv.org/content/10.64898/2026.04.10.717844v1"
    },
    {
      "id": "pubmed_40790933",
      "title": "Could the Polymorphisms of DOCK4, SYNGAP1, and FOXP1 be the Primary Risk Factors for Bipolar Disorder and ASD?",
      "authors": "Ciftci E, Saglam N, Gozler T, et al.",
      "journal": "Developmental Neurobiology",
      "date": "2025-10-01",
      "source": "pubmed",
      "score": 11,
      "decision": "REVIEW",
      "genes_mentioned": [
        "FOXP1",
        "SYNGAP1"
      ],
      "summary": "Small Turkish genotyping study (n=200) of FOXP1/SYNGAP1/DOCK4 SNPs in ASD and bipolar. Negative result, underpowered.",
      "doi": "10.1002/dneu.22995",
      "url": "https://pubmed.ncbi.nlm.nih.gov/40790933/"
    }
  ]
};
