// Auto-generated by atlas-daily-scan — 2026-04-14
window.PAPERS_FEED = {
  "last_updated": "2026-04-14",
  "papers": [
    {
      "id": "41974488",
      "title": "FKH-7/FOXP1 in C. elegans chemosensory neurons shapes life history strategy",
      "authors": "Chai CM et al.",
      "journal": "Genetics",
      "date": "2026-04-14",
      "source": "pubmed",
      "score": 26,
      "decision": "INTEGRATE",
      "genes_mentioned": [
        "FOXP1"
      ],
      "summary": "Human FOXP1 substitutes for C. elegans FKH-7; NDD missense variant reduces adaptive response; single-cell transcriptomics of variant effects.",
      "doi": "10.1093/genetics/iyag099",
      "url": "https://doi.org/10.1093/genetics/iyag099"
    },
    {
      "id": "10.64898/2026.01.20.700519",
      "title": "Federated single-cell QTL meta-analysis reveals novel disease mechanisms",
      "authors": "Kaptijn D et al.",
      "journal": "bioRxiv",
      "date": "2026-04-14",
      "source": "biorxiv",
      "score": 28,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "Single-cell eQTLs invisible in bulk are MORE enriched for disease GWAS loci; reconstructed 6,382 trans-eGenes with directed regulatory networks.",
      "doi": "10.64898/2026.01.20.700519",
      "url": "https://www.biorxiv.org/content/10.64898/2026.01.20.700519v1"
    },
    {
      "id": "41978434",
      "title": "Functional characterization of 42 CK2alpha de novo variants associated with Okur-Chung neurodevelopmental syndrome",
      "authors": "Gast A et al.",
      "journal": "FEBS J",
      "date": "2026-04-13",
      "source": "pubmed",
      "score": 18,
      "decision": "INTEGRATE",
      "genes_mentioned": [
        "CSNK2A1"
      ],
      "summary": "42 CK2alpha variants in OCNDS characterized; 13 had zero activity, some retained normal function suggesting non-enzymatic pathogenic mechanisms.",
      "doi": "10.1111/febs.70538",
      "url": "https://doi.org/10.1111/febs.70538"
    },
    {
      "id": "10.64898/2026.04.09.26350245",
      "title": "Tic Disorders GWAS: 6 Risk Loci including HCN1",
      "authors": "Yu D et al.",
      "journal": "medRxiv",
      "date": "2026-04-13",
      "source": "medrxiv",
      "score": 29,
      "decision": "INTEGRATE",
      "genes_mentioned": [
        "HCN1",
        "PCDH9"
      ],
      "summary": "GWAS of 13K tic cases identifies HCN1 as risk gene; highlights D1/D2 MSNs and cortical pyramidal neurons; genetic correlations with NDD.",
      "doi": "10.64898/2026.04.09.26350245",
      "url": "https://www.biorxiv.org/content/10.64898/2026.04.09.26350245v1"
    },
    {
      "id": "10.64898/2026.04.10.26349224",
      "title": "Shared genetic architecture of cortical morphology and psychiatric disorders",
      "authors": "Zhang Y et al.",
      "journal": "medRxiv",
      "date": "2026-04-13",
      "source": "medrxiv",
      "score": 23,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "NDD share fewer but more widespread-effect loci with cortical morphology than internalizing disorders; directional heterogeneity limits prediction.",
      "doi": "10.64898/2026.04.10.26349224",
      "url": "https://www.biorxiv.org/content/10.64898/2026.04.10.26349224v1"
    },
    {
      "id": "10.64898/2026.04.09.26350474",
      "title": "De novo mutation timing and selection in male germline",
      "authors": "Neville MDC et al.",
      "journal": "medRxiv",
      "date": "2026-04-13",
      "source": "medrxiv",
      "score": 26,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "168 trios + sperm duplex sequencing: most DD fathers have normal sperm mutation burden; ~11% of pathogenic burden from early mosaicism.",
      "doi": "10.64898/2026.04.09.26350474",
      "url": "https://www.biorxiv.org/content/10.64898/2026.04.09.26350474v1"
    },
    {
      "id": "41974886",
      "title": "Response: Nrp2 deletion in interneurons - autism/seizure behaviors",
      "authors": "Subramanian D et al.",
      "journal": "Mol Psychiatry",
      "date": "2026-04-13",
      "source": "pubmed",
      "score": 10,
      "decision": "REVIEW",
      "genes_mentioned": [
        "NRP2"
      ],
      "summary": "Letter regarding interneuron-specific Nrp2 deletion affecting hippocampal circuits.",
      "doi": "10.1038/s41380-026-03546-y",
      "url": "https://doi.org/10.1038/s41380-026-03546-y"
    },
    {
      "id": "biorxiv_10.1101_2024.05.26.595966",
      "title": "Complementary vertebrate Wac models exhibit phenotypes relevant to DeSanto-Shinawi Syndrome",
      "authors": "Lee K-H, Stafford AM, Pacheco-Vergara M, et al.",
      "journal": "bioRxiv",
      "date": "2026-04-12",
      "source": "biorxiv",
      "score": 23,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "First comprehensive vertebrate WAC models. Mouse and zebrafish knockouts show GABAergic neuron impacts, seizure susceptibility, and autism-relevant behaviors.",
      "doi": "10.1101/2024.05.26.595966",
      "url": "https://www.biorxiv.org/content/10.1101/2024.05.26.595966v4"
    },
    {
      "id": "biorxiv_10.64898_2026.04.10.717844",
      "title": "EVEE: Interpretable variant effect prediction from genomic foundation model embeddings",
      "authors": "Pearce MT, Dooms T, Yamamoto R, et al.",
      "journal": "bioRxiv",
      "date": "2026-04-11",
      "source": "biorxiv",
      "score": 25,
      "decision": "INTEGRATE",
      "genes_mentioned": [],
      "summary": "SOTA variant effect prediction using Evo 2 7B-parameter genomic foundation model. 0.997 AUROC on 839k ClinVar SNVs. Pre-computed for 4.2M ClinVar variants via EVEE web tool.",
      "doi": "10.64898/2026.04.10.717844",
      "url": "https://www.biorxiv.org/content/10.64898/2026.04.10.717844v1"
    },
    {
      "id": "41977462",
      "title": "Unraveling the Genetic and Molecular Architecture of Autism Spectrum Disorder",
      "authors": "Treccarichi S et al.",
      "journal": "Int J Mol Sci",
      "date": "2026-04-04",
      "source": "pubmed",
      "score": 18,
      "decision": "INTEGRATE",
      "genes_mentioned": [
        "SHANK3",
        "SYNGAP1",
        "CHD8",
        "ADNP",
        "ARID1B",
        "MECP2"
      ],
      "summary": "Review of ASD genetic architecture: CNVs, SNVs, convergent pathways, diagnostic yield limitations.",
      "doi": "10.3390/ijms27073278",
      "url": "https://doi.org/10.3390/ijms27073278"
    },
    {
      "id": "41972553",
      "title": "Cytoskeletal Dynamics and Molecular Motor Dysfunction in SZ and ASD",
      "authors": "Nakamura K et al.",
      "journal": "Biology",
      "date": "2026-03-30",
      "source": "pubmed",
      "score": 10,
      "decision": "REVIEW",
      "genes_mentioned": [
        "SHANK3"
      ],
      "summary": "Review of cytoskeletal/molecular motor abnormalities in schizophrenia and ASD.",
      "doi": "10.3390/biology15070550",
      "url": "https://doi.org/10.3390/biology15070550"
    },
    {
      "id": "pubmed_40790933",
      "title": "Could the Polymorphisms of DOCK4, SYNGAP1, and FOXP1 be the Primary Risk Factors for Bipolar Disorder and ASD?",
      "authors": "Ciftci E, Saglam N, Gozler T, et al.",
      "journal": "Developmental Neurobiology",
      "date": "2025-10-01",
      "source": "pubmed",
      "score": 11,
      "decision": "REVIEW",
      "genes_mentioned": [
        "FOXP1",
        "SYNGAP1"
      ],
      "summary": "Small Turkish genotyping study (n=200) of FOXP1/SYNGAP1/DOCK4 SNPs in ASD and bipolar. Negative result, underpowered.",
      "doi": "10.1002/dneu.22995",
      "url": "https://pubmed.ncbi.nlm.nih.gov/40790933/"
    }
  ]
};
